name: ecommerce_app_riverpod_getx
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.7.0
  dio: ^5.4.3+1
  get: ^4.6.6
  intl: ^0.19.0
  smooth_page_indicator: ^1.1.0
  get_storage: ^2.1.1
  flutter_spinkit: ^5.2.1
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets\fonts\Roboto-Bold.ttf
          weight: 700
   
  #

